# Generated by Django 2.0.1 on 2018-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketlist',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
